import 'package:audio_wave/audio_wave.dart';
import 'package:flutter/material.dart';

class CustomAudioWave extends StatelessWidget {
  final bool animation;
  final BuildContext context;

  CustomAudioWave({this.animation = false, required this.context});

  Widget build(BuildContext _context) {
    return AudioWave(
      height: MediaQuery.of(context).size.height / 4,
      width: MediaQuery.of(context).size.width,
      spacing: 4,
      animation: animation,
      animationLoop: 0,
      beatRate: Duration(milliseconds: 100),
      bars: [
        AudioWaveBar(heightFactor: .10, color: Colors.black, radius: 0),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .100, color: Colors.black),
        AudioWaveBar(heightFactor: .90, color: Colors.black),
        AudioWaveBar(heightFactor: .80, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black, radius: 0),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .100, color: Colors.black),
        AudioWaveBar(heightFactor: .90, color: Colors.black),
        AudioWaveBar(heightFactor: .80, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black, radius: 0),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .100, color: Colors.black),
        AudioWaveBar(heightFactor: .90, color: Colors.black),
        AudioWaveBar(heightFactor: .80, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black, radius: 0),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .100, color: Colors.black),
        AudioWaveBar(heightFactor: .90, color: Colors.black),
        AudioWaveBar(heightFactor: .80, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
      ],
    );
  }
}

class StoppedAudioWave extends StatelessWidget {
  final BuildContext context;

  StoppedAudioWave({required this.context});

  Widget build(BuildContext _context) {
    return AudioWave(
      height: MediaQuery.of(context).size.height / 4,
      width: MediaQuery.of(context).size.width,
      spacing: 4,
      animation: false,
      bars: [
        AudioWaveBar(heightFactor: .10, color: Colors.black, radius: 0),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .100, color: Colors.black),
        AudioWaveBar(heightFactor: .90, color: Colors.black),
        AudioWaveBar(heightFactor: .80, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black, radius: 0),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .100, color: Colors.black),
        AudioWaveBar(heightFactor: .90, color: Colors.black),
        AudioWaveBar(heightFactor: .80, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black, radius: 0),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .100, color: Colors.black),
        AudioWaveBar(heightFactor: .90, color: Colors.black),
        AudioWaveBar(heightFactor: .80, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
        AudioWaveBar(heightFactor: .10, color: Colors.black, radius: 0),
        AudioWaveBar(heightFactor: .30, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .100, color: Colors.black),
        AudioWaveBar(heightFactor: .90, color: Colors.black),
        AudioWaveBar(heightFactor: .80, color: Colors.black),
        AudioWaveBar(heightFactor: .70, color: Colors.black),
        AudioWaveBar(heightFactor: .40, color: Colors.black),
        AudioWaveBar(heightFactor: .20, color: Colors.black),
      ],
    );
  }
}
